### ISSUE TITLE
Feature Request: Hcaptcha

### ISSUE THREAD

**Issue by ghost** [FriendsOfFlarum/recaptcha#14]
Hi, 

Would there be any possibility of integrating Hcaptcha with this extension? 

Maybe we could have an option in the admin panel to enable either Recaptcha or Hcaptcha?  

https://www.hcaptcha.com/

**Comment by Unkorneglosk** [comment]
I agree. And most of the code could be the same as both APIs are very similar. 
https://docs.hcaptcha.com/switch

**Comment by Ralkage** [comment]
I went ahead and created a separate extension for hCaptcha for Flarum :) please see https://github.com/Ralkage/flarum-hcaptcha
