### ISSUE TITLE
Include recaptcha script only in register modal

### ISSUE THREAD

**Issue by XakepSDK** [FriendsOfFlarum/recaptcha#2]
Extension works only in registration modal, but script loads in every page. That's bad.

**Comment by luceos** [comment]
It's a SPA, meaning the HEAD is generated once and re-used everywhere.

**Comment by datitisev** [comment]
I guess it could be made so it only adds the reCAPTCHA code to the head when viewing as a guest, aka when there's no user signed in.. there's no point in having the code load when a user has signed in.

Thoughts?
