### ISSUE TITLE
recaptcha in China fix

### ISSUE THREAD

**Issue by anglesgirl** [FriendsOfFlarum/recaptcha#27]
In China, you need to modify the domain name of Google recaptcha to

https://www.google.com/recaptcha/api.js
change to
https://recaptcha.net/recaptcha/api.js

https://www.google.com/recaptcha/api/siteverify  
change to
https://recaptcha.net/recaptcha/api/siteverify

**Comment by Ralkage** [comment]
Hello there 👋 there's already a PR open for this request https://github.com/FriendsOfFlarum/recaptcha/pull/25; we'll review as a team and see if it makes sense to add this change in a future release :)
