### ISSUE TITLE
Broke Beta 12: not compatible with Beta 12. Will wait a fix for upgrade to Beta 12

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/recaptcha#7]
Hi, the extension is not compatible with Beta 12 cause the community to not load.
Hope the fix can be made so i can upgrade to Beta 12.

I never want a community without the security check of ReCaptcha ;)

https://discuss.flarum.org/d/22982-cannot-upgrade-to-beta-12

**Comment by PeopleInside** [comment]
I edited the two file but issue persist, what i have to do?
Need recompile with some command? I have my PI community down do i cannot read the recompile solution.. I need to look at this issue... umh.. I edited the two files here but still not work. What i have to do?

Thanks

**Comment by datitisev** [comment]
Composer needs to re-create the namespaces, so you still need to run it.

**Comment by PeopleInside** [comment]
What i have to run?

**Comment by datitisev** [comment]
I don't think you can run any of the composer commands without having your edits overwritten. Not sure though.

**Comment by PeopleInside** [comment]
How can have the fix on my communities? What i have to do?

**Comment by datitisev** [comment]
You can update fof/recaptcha to 0.1.2. Apologies if that's what you wanted - from your comment, I thought you weren't able to download the new update (which I didn't mention when I closed the issue).

**Comment by PeopleInside** [comment]
Thanks. is not showed the ReCaptcha on login page only on register page?
Is not possible protect also the logins? Need request a feature request?
I was thinking the protection was login and registration.
