### ISSUE TITLE
Feature request: add option to protect also the login form

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/recaptcha#8]
Hi, I see the protection is active on the registration,
why not protect also the login form? This can help to prevent automated system trying to login.

Please consider to add a check box that allow this as option in the settings.

Security feature as this will add protection on login form.

**Comment by askvortsov1** [comment]
I'm not sure of the use case for this. You'd need valid credentials to login, as opposed to registration where a bot could register thousands of fake accounts.

**Comment by PeopleInside** [comment]
Umh a bot can try to guess password. The ReCaptcha can block robots.
I use ReCaptcha in login for example in the open source live helper chat.

The idea is protect login from bot's

**Comment by Niksend** [comment]
I support this proposal.Bots from internet will try to crack users password if there is nothing to filter them out.

**Comment by Sharen2020** [comment]
I have the same problem. Do you have a solution?

**Comment by Sharen2020** [comment]
Because the risk of brute force cracking user password can be effectively reduced by adding reCAPTCHA to the login page.

**Comment by Ralkage** [comment]
Since this was brought up again via https://github.com/FriendsOfFlarum/recaptcha/issues/21; I'll have a chat with the team internally to see if we can implement these features in a future release :)

**Comment by imorland** [comment]
This will become possible to implement when https://github.com/flarum/framework/pull/3670 is available

I'll circle back here when it's merged and released!

**Comment by PeopleInside** [comment]
Hi, thanks for the update but the update has issue on login page:
unable to login and captcha showed wrong.
https://github.com/FriendsOfFlarum/recaptcha/issues/39
